# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: postgresql
  encoding: unicode
  database: sphnix
  pool: 5
  host: localhost
  username: postgres
  password: ajin




staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
